FROM openjdk-11
WORKDIR /opt
COPY target/data-submit-wrapper-1.0.0-SNAPSHOT-runner.jar /opt/data-submit-wrapper-1.0.0-SNAPSHOT-runner.jar
RUN ls
RUN pwd
EXPOSE 9084
ENTRYPOINT ["java","-jar","data-submit-wrapper-1.0.0-SNAPSHOT-runner.jar"]
~                                                                                                                                                                       
~                                                                                                    
