FROM openjdk-11
WORKDIR /opt

COPY target/aadharduplicationcheck-1.0.0-SNAPSHOT-runner.jar /opt/aadharduplicationcheck-1.0.0-SNAPSHOT-runner.jar
EXPOSE 7010
RUN ls
RUN pwd
ENTRYPOINT ["java","-jar","aadharduplicationcheck-1.0.0-SNAPSHOT-runner.jar"]
~                                                                                                                                                                       
~                                                                                                                                                                       
