FROM openjdk-11
WORKDIR /opt
COPY target/check-key-infinispan-1.0.0-SNAPSHOT-runner.jar /opt/check-key-infinispan-1.0.0-SNAPSHOT-runner.jar
RUN ls
RUN  pwd
EXPOSE 11222
ENTRYPOINT ["java","-jar","check-key-infinispan-1.0.0-SNAPSHOT-runner.jar"]
~                                                                                                                                                                       
~                                                                                                                                                                       
~                                                                                                                                                                       
~                                                                                                                                                                       
~                                                                                                                                                                       

